version: 2

models:
  - name: stg_yellow_trips
    description: "Staging model for yellow taxi trips, cleaned and renamed from raw source."
    columns:
      - name: VendorID
        description: "Identifier for the taxi company."
        tests:
          - not_null
      - name: tpep_pickup_datetime
        description: "Date and time when the meter was engaged."
        tests:
          - not_null
      - name: tpep_dropoff_datetime
        description: "Date and time when the meter was disengaged."
        tests:
          - not_null
      - name: passenger_count
        description: "Number of passengers in the trip."
      - name: trip_distance
        description: "Distance of the trip in miles."
      - name: RatecodeID
        description: "Rate code assigned to the trip."
      - name: PULocationID
        description: "Pickup location ID."
        tests:
          - not_null
      - name: DOLocationID
        description: "Dropoff location ID."
        tests:
          - not_null
      - name: store_and_fwd_flag
        description: "Whether the trip record was held in vehicle memory before sending."
      - name: payment_type
        description: "Payment method used."
      - name: fare_amount
        description: "Base fare for the trip."
      - name: extra
        description: "Miscellaneous extras (e.g., surcharge)."
      - name: mta_tax
        description: "MTA tax."
      - name: tip_amount
        description: "Tip amount paid by passenger."
      - name: tolls_amount
        description: "Tolls charged during the trip."
      - name: total_amount
        description: "Total amount paid by passenger."
      - name: congestion_surcharge
        description: "Congestion surcharge, if applicable."

  - name: fact_trips
    description: "Fact table for yellow taxi trips containing core transactional data."
    columns:
      - name: tpep_pickup_datetime
        description: "Pickup timestamp of the trip."
      - name: tpep_dropoff_datetime
        description: "Dropoff timestamp of the trip."
      - name: passenger_count
        description: "Number of passengers."
      - name: trip_distance
        description: "Trip distance in miles."
      - name: fare_amount
        description: "Base fare amount."
      - name: tip_amount
        description: "Tip paid by the rider."
      - name: tolls_amount
        description: "Toll charges during the ride."
      - name: total_amount
        description: "Total fare paid."
      - name: PULocationID
        description: "Pickup location."
      - name: DOLocationID
        description: "Dropoff location."
      - name: payment_type
        description: "Payment method."

  - name: dim_datetime
    description: "Dimension table for datetime features extracted from pickup timestamps."
    columns:
      - name: datetime
        description: "The original timestamp (pickup time)."
        tests:
          - unique
          - not_null
      - name: hour
        description: "Hour of the day."
      - name: day
        description: "Day of the month."
      - name: week
        description: "Week number of the year."
      - name: month
        description: "Month number."
      - name: year
        description: "Year value."
      - name: day_name
        description: "Day name (e.g., Monday)."

  - name: dim_zones
    description: "Dimension table for taxi zones."
    columns:
      - name: zone_id
        description: "Unique location ID for the zone."
        tests:
          - unique
          - not_null
      - name: Borough
        description: "Borough name (e.g., Manhattan)."
      - name: Zone
        description: "Taxi zone name."
      - name: service_zone
        description: "Service zone category (e.g., Boro, Airports)."
